export const THEMES = {
  obsidian: { name: 'Obsidian Crown', accent: '♛', line: '━━━━━━━━━━━━━━━━━━', status: 'NIGHTWATCH' },
  neon: { name: 'Neon Circuit', accent: '◈', line: '══════════════════', status: 'CYBERLINK' },
  frost: { name: 'Frost Protocol', accent: '❄', line: '┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄', status: 'CRYOCORE' },
  royal: { name: 'Royal Command', accent: '♚', line: '◆━━━━━━━━━━━━━━◆', status: 'SOVEREIGN' },
  matrix: { name: 'Matrix Grid', accent: '▣', line: '0101010101010101', status: 'GRIDRUNNER' }
};

const definitions = [
  ['group.dashboard','Group Dashboard','Group','Open the live group HUD'], ['group.rules','Rules Center','Group','View and format rules'], ['group.welcome','Welcome Studio','Group','Design welcome messages'], ['group.settings','Settings Matrix','Group','Inspect group protection state'], ['group.members','Member Directory','Group','Review visible member status'], ['group.admins','Admin Console','Group','Review administrator roles'], ['group.id','Identity Lens','Group','Inspect chat and user IDs'], ['group.stats','Activity Intelligence','Group','View message and action counts'], ['group.audit','Audit Timeline','Group','Review moderation actions'], ['group.notes','Group Notes','Group','Store non-sensitive admin notes'],
  ['protect.antilink','Anti-link Shield','Protection','Filter links from non-admins'], ['protect.antispam','Anti-spam Core','Protection','Filter oversized flood messages'], ['protect.lock','Lockdown Switch','Protection','Lock or unlock member messaging'], ['protect.warn','Warning Engine','Protection','Manage member warnings'], ['protect.mute','Mute Protocol','Protection','Temporarily restrict a member'], ['protect.ban','Ban Protocol','Protection','Ban a member with confirmation'], ['protect.kick','Kick Protocol','Protection','Remove a member without a permanent ban'], ['protect.purge','Message Purge','Protection','Delete a bounded message range'], ['protect.report','Report Relay','Protection','Send a report to administrators'], ['protect.pin','Pin Control','Protection','Pin or unpin approved messages'],
  ['content.announce','Announcement Composer','Content','Format a group announcement'], ['content.poll','Poll Builder','Content','Create a structured poll draft'], ['content.checklist','Checklist Maker','Content','Create an action checklist'], ['content.faq','FAQ Builder','Content','Generate a reusable FAQ template'], ['content.template','Template Vault','Content','Save reusable admin templates'], ['content.markdown','Markdown Studio','Content','Preview safe Telegram formatting'], ['content.json','JSON Inspector','Content','Validate small JSON payloads'], ['content.regex','Regex Coach','Content','Explain a regular expression'], ['content.translate','Translation Desk','Content','Prepare text for translation APIs'], ['content.summarize','Summary Desk','Content','Prepare text for summarization APIs'],
  ['utility.calculator','Calculator','Utility','Evaluate basic arithmetic safely'], ['utility.uuid','UUID Forge','Utility','Generate a random UUID'], ['utility.qr','QR Builder','Utility','Prepare a QR payload'], ['utility.color','Color Lab','Utility','Inspect a color value'], ['utility.time','Time Lens','Utility','Show a timezone-aware time'], ['utility.weather','Weather Lens','Utility','Prepare a weather lookup'], ['utility.currency','Currency Lens','Utility','Prepare a currency lookup'], ['utility.url','URL Inspector','Utility','Normalize a URL'], ['utility.hash','Hash Utility','Utility','Hash non-sensitive text locally'], ['utility.uptime','Uptime Monitor','Utility','Show bot process health'],
  ['owner.pro','Pro Access','Owner','Inspect owner and premium status'], ['owner.tier','Tier Manager','Owner','View current entitlement tier'], ['owner.grant','Grant Premium','Owner','Grant premium to a chat'], ['owner.revoke','Revoke Premium','Owner','Revoke premium from a chat'], ['owner.theme','Theme Control','Owner','Select a HUD theme'], ['owner.plugins','Plugin Registry','Owner','Inspect enabled plugins'], ['owner.apis','API Control','Owner','Inspect enabled API modules'], ['owner.health','Health Matrix','Owner','Inspect runtime health'], ['owner.backup','Backup Manager','Owner','Prepare a state backup'], ['owner.restore','Restore Manager','Owner','Prepare a state restore'], ['owner.maintenance','Maintenance Mode','Owner','View maintenance status'], ['owner.changelog','Release Notes','Owner','Show platform release notes'], ['owner.debug','Diagnostics','Owner','Show safe diagnostic metadata'],
  ['api.webhook','Webhook Gateway','Integration','Configure an authorized webhook'], ['api.rss','RSS Reader','Integration','Read an approved RSS feed'], ['api.github','GitHub Lens','Integration','Read repository metadata'], ['api.status','Statuspage Lens','Integration','Read a public service status'], ['api.weather','Weather API','Integration','Use a configured weather provider'], ['api.geocode','Geocode API','Integration','Use a configured geocoding provider'], ['api.currency','Currency API','Integration','Use a configured exchange provider'], ['api.translate','Translation API','Integration','Use a configured translation provider'], ['api.moderation','Moderation API','Integration','Use a configured content-safety provider'], ['api.calendar','Calendar Bridge','Integration','Prepare an authorized calendar event'], ['api.sheets','Sheets Bridge','Integration','Prepare an authorized spreadsheet write'], ['api.drive','Drive Bridge','Integration','Prepare an authorized file operation'], ['api.notion','Notion Bridge','Integration','Prepare an authorized page update'], ['api.slack','Slack Relay','Integration','Relay to an authorized workspace'], ['api.discord','Discord Relay','Integration','Relay to an authorized server'], ['api.email','Email Relay','Integration','Prepare an authorized notification'], ['api.analytics','Analytics Export','Integration','Export aggregated bot metrics'], ['api.tempmail_test','Test Inbox Adapter','Integration','Use only for approved QA test inboxes'], ['api.backup','Cloud Backup Adapter','Integration','Prepare an encrypted backup upload'], ['api.scheduler','Task Scheduler','Integration','Prepare a bounded recurring task']
].map(([id, name, category, description]) => ({ id, name, category, description }));

export const PRO_TOOLS = definitions;
export const API_MODULES = PRO_TOOLS.filter((tool) => tool.category === 'Integration');

export function isOwner(userId, ownerId) { return Boolean(ownerId && Number(userId) === Number(ownerId)); }
export function entitlementFor({ userId, chatId, ownerId, premiumChats = [] }) {
  if (isOwner(userId, ownerId)) return { tier: 'OWNER', label: 'SOVEREIGN OWNER', unlimited: true };
  if (premiumChats.map(Number).includes(Number(chatId))) return { tier: 'PRO', label: 'PRO ACCESS', unlimited: false };
  return { tier: 'CORE', label: 'CORE ACCESS', unlimited: false };
}
export function themeFor(name = 'obsidian') { return THEMES[name] || THEMES.obsidian; }
export function toolsByCategory(category) { return PRO_TOOLS.filter((tool) => tool.category === category); }
export function renderToolCatalog(category) {
  const tools = category ? toolsByCategory(category) : PRO_TOOLS;
  return tools.map((tool, index) => `<code>${String(index + 1).padStart(2, '0')}</code> <b>${tool.name}</b> — ${tool.description}`).join('\n');
}
export function safeApiPolicy() {
  return 'API modules are disabled by default, require explicit provider keys, use bounded requests, and must not be used for spam, credential collection, mass messaging, access bypass, or disposable-account abuse.';
}
